import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import LeftSideBar from "@/components/ui/LeftSideBar";
import SessionWrapper from "@/hooks/SessionWrapper";
import RightsideBar from "@/components/ui/RightsideBar";
import { ThemeProvider } from "@/components/theme-provider";
import MobileBottomNav from "@/components/ui/MobileBottomNav";
import MobileHeader from "@/components/ui/MobileHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <SessionWrapper>
            {/* Mobile Header */}
            <MobileHeader />
            <div className="flex min-h-screen max-w-7xl mx-auto relative bg-background pt-14 lg:pt-0">
              {/* Left Sidebar - Desktop Only */}
              <div className="lg:w-[5%] border-r border-border hidden lg:block">
                <LeftSideBar />
              </div>
              <main className="w-full max-w-2xl mx-auto pb-16 lg:pb-0">
                {children}
              </main>
            </div>
            {/* Mobile Bottom Navigation */}
            <MobileBottomNav />
          </SessionWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
