import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import LeftSideBar from "@/components/ui/LeftSideBar";
import SessionWrapper from "@/hooks/SessionWrapper";
import RightsideBar from "@/components/ui/RightsideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div className="flex min-h-screen max-w-7xl mx-auto relative">
          {/* Left Sidebar */}
          <div className="lg:w-[5%] border-r border-gray-700 hidden lg:block">
            <LeftSideBar />
          </div>
          <main className="w-full max-w-2xl mx-auto">
            <SessionWrapper>{children}</SessionWrapper>
          </main>

          <div className="hidden lg:block absolute right-0 top-0 w-[250px] p-4">
            <RightsideBar />
          </div>
        </div>
      </body>
    </html>
  );
}
