import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import LeftSideBar from "@/components/ui/LeftSideBar";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div className="flex min-h-screen max-w-7xl mx-auto">
          <div className="  lg:w-[5%] lg:border-0 lg:border-r border-gray-700">
            <LeftSideBar />
          </div>
          <main className="w-full lg:w-[90%]">{children}</main>
        </div>
      </body>
    </html>
  );
}
